spring.application.name=database2
spring.datasource.url=jdbc:postgresql://localhost:6767/postgres
spring.datasource.username=strajja
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update