spring.application.name=training6
spring.datasource.url=jdbc:postgresql://localhost:6767/postgres
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always